domain: cn.ubuntu.com

image: prod-comms.ps5.docker-registry.canonical.com/cn.ubuntu.com

env:
  - name: SENTRY_DSN
    value: https://06096678a069442f9e6f72aa985f15ca@sentry.is.canonical.com//32

  - name: DISCOURSE_API_KEY
    secretKeyRef:
      key: ubuntu-api-key
      name: discourse-api

  - name: DISCOURSE_API_USERNAME
    secretKeyRef:
      key: ubuntu-api-username
      name: discourse-api

  - name: COOKIE_SERVICE_API_KEY
    secretKeyRef:
      key: cookies-api-key
      name: cookies-canonical-com-credentials
  
  - name: WORDPRESS_APPLICATION_PASSWORD
    secretKeyRef:
      key: wordpress-application-password
      name: wordpress-api

  - name: WORDPRESS_USERNAME
    secretKeyRef:
      key: wordpress-username
      name: wordpress-api

useProxy: false

readinessPath: "/_status/ping"

demo:
  env:
    - name: HTTP_PROXY
      value: http://squid.internal:3128

    - name: HTTPS_PROXY
      value: http://squid.internal:3128

    - name: NO_PROXY
      value: "10.24.0.132,10.24.0.23,.internal,admin.insights.ubuntu.com,ubuntu.com,.ubuntu.com,snapcraft.io,.snapcraft.io,jujucharms.com,.jujucharms.com,maas.io,.maas.io,conjure-up.io,.conjure-up.io,netplan.io,.netplan.io,canonical.com,.canonical.com,launchpad.net,.launchpad.net,linuxcontainers.org,.linuxcontainers.org,cloud-init.io,.cloud-init.io,vanillaframework.io,.vanillaframework.io,anbox-cloud.io,.anbox-cloud.io,juju.is,.juju.is,dqlite.io,.dqlite.io,charmhub.io,.charmhub.io,canonical.design,.canonical.design"

extraHosts:
  - domain: ubuntu-china.cn
    useParentTLS: True

# Overrides for production
production:
  replicas: 5
  nginxConfigurationSnippet: |
    if ($host != 'cn.ubuntu.com' ) {
      rewrite ^ https://cn.ubuntu.com$request_uri? permanent;
    }
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";

# Overrides for staging
staging:
  replicas: 3
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
